### ISSUE TITLE
question: why we have build workflow on `ancient` compiler?

### ISSUE THREAD

**Issue by 6293** [LNP-BP/rust-amplify#116]
I am not really bothered by this though. just out of curiosity

**Comment by 6293** [comment]
`bug` label by mistake

**Comment by dr-orlovsky** [comment]
This is due to the idea of using this library in rust-bitcoin at some point. They do use ancient version to support alternative rust compilers and bootstrapping from C

**Comment by 6293** [comment]
I see. thanks for answering
