### ISSUE TITLE
Turn on overflow checks in non-codecov tests

### ISSUE THREAD

**Issue by Kixunil** [LNP-BP/rust-amplify#16]
I noticed this in test configuration and I'm wondering why overflow checks are off.
Overflows are considered bugs in Rust unless explicit wrapping or saturation is used.

**Comment by dr-orlovsky** [comment]
Because this is the way grcov and codecov are work with: their rust settings. It's not about testing how it will work in production, it's about testing coverage of the code.

**Comment by Kixunil** [comment]
I'm not familiar with GitHub actions config but I don't see tests with the checks enabled. Maybe they should be enabled in separate tests?

**Comment by dr-orlovsky** [comment]
I think we can have it as a separate test, true. I will work on that.

The workflow/action is here: https://github.com/LNP-BP/rust-amplify/blob/master/.github/workflows/test.yml
