### ISSUE TITLE
Separate CowHelper and stringly macros to other crates?

### ISSUE THREAD

**Issue by Kixunil** [LNP-BP/rust-amplify#7]
I'm now writing an independent project that could make use of these little helpers but depending on `rust-amplify` is too much (also I want MSRV to be at most 1.41). Rather than copy-pasting I'd like to separate them to their own crates and refactor them for higher quality. I'm willing to do the work of course.

Suggested changes:

* Rename `CowHelper` to `TryFromStrHelper` and move to a crate called `serde_try_from_str_helper`
* Make sure the documentation is understandable.
* `impl<'a> From<Cow<'a, str>> for TryFromStrHelper<'a>`- this and the following impls may be useful for a fancier deserialization and looks nicer
* `impl<'a> From<TryFromStrHelper<'a>> for Cow<'a, str>`
* `impl<'a> AsRef<Cow<'a, str>> for TryFromStrHelper<'a>` 
* `impl<'a> AsMut<Cow<'a, str>> for TryFromStrHelper<'a>`
* `impl<'a> Borrow<Cow<'a, str>> for TryFromStrHelper<'a>`
* `impl<'a> BorrowMut<Cow<'a, str>> for TryFromStrHelper<'a>`
* `impl<'a> AsRef<str> for TryFromStrHelper<'a>`
* Maybe instantly stabilize (`1.0`) because of simplicity?
* Move the macros to a crate called `stringly_conversions`
* Define compatibility rules: when we can add another type to the "standard" macros? Suggested rules:
     * We can add a type added in `std` at any time.
     * We can add a type from another crate, where the type was introduced in a release not older than 24 hours.
     * Crate authors who wish to be added must reach out before releasing a new version.
* Do not stabilize yet - announce it and wait for wider Rust community to suggest additional types.

Questions:

* Should these crates belong to LNP-BP org? I don't see a problem rigth now but LMK if there's some.
* Do the names make sense?
* Are there other things that should be changed?

**Comment by dr-orlovsky** [comment]
I think overall idea is great!

Few considerations/questions:
1. I do not understand Cow name, what it mean other than an animal :)
2. I am a bit afraid of crate names of big length with a lot of `_` inside. May be a single `serde_helpers` crate with all this blocks (like `try_from_str`) as a features?
3. I will be happy to have it under LNP/BP! Can we also make it a part of this repo workspace just to reduce the number of different repos all around? Also, the whole idea of `amplify` crate is to have this small different additions to the core, std and serde libs that are useful everywhere, so I am ok with even having it as a just feature under the main `amplify` crate. If you don't need the rest of features, I think it will be good to convert each `amplify` mod to a feature, so users can take only those they need. This is especially important in crypto projects, where each dependency is a huge concern, and having many of them are very not welcome in the community.
4. Version `1.0` - agree; regarding waiting for the community - can start it as a sub-crate here with some minor version and later convert it to the feature under main crate (which is already more or less stabilized)
5. The rest looks fine to me!

**Comment by dr-orlovsky** [comment]
@Kixunil btw you are already a member here in LNP/BP org as a part of "core devs" team with all necessary rights to admin this repo

**Comment by dr-orlovsky** [comment]
Regarding rustc 1.41 support: it's done <https://github.com/LNP-BP/rust-amplify/pull/8>

**Comment by Kixunil** [comment]
1. `Cow` is short from "Clone on write" and it was previously called `CowHelper` becuase it contains `Cow`. However naming it by what it does instead of how it's implemented is much better. :)
2. I prefer short names as well but not at the cost of clarity. Maybe `serde_str_helpers`?
3. The fear of *raw count* of dependencies is misplaced IMO. Raw count is mostly meaningless. More relevant questions should be: How many lines of code are there? How many people maintain it? What's the reputation of those people? If the answer is "we have two more very simple crates from reputable people" I don't see a huge problem. To the contrary, it's easier to review the source code of a small crate than the source code of large crate with features. (Do the features really turn off everything not needed?) I do understand that the fear of dependencies is historically developed because there weren't great dependency managers before cargo but I don't see a good reason to stall development in this area. That being said, keeping it in a single git repository (at least for now) sounds fine.

**Comment by Kixunil** [comment]
Decided to call the type `DeserStrHelper` to more clearly convey that the point is deserialization, not conversion.

**Comment by dr-orlovsky** [comment]
1. I see  `DeserStrHelper`👍🏻 
2. `serde_str_helpers` is fine!
3. You are absolutely right. However, as a consequence of what you said, you have to _count_ absolute number of deps as a number of "points of trust" to a team/maintainers (one per dep), so it also matters a lot.

**Comment by Kixunil** [comment]
3. Rght, I was thinking that having a tool to do the counting would be nice. Maybe something for `cargo-audit`

So since you want to support < 1.41.1 I will need to add a feature (I'll call it `rust_1_41`) since I also implemented `From<> for Cow`. Without the feature, only `Into` will be implemented.

I have also decided to not implement `AsRef` and similar things that leak internal representation in case we want to change it (e.g. using insane `String` trick with capacity = 0).

I'm almost done with helpers crate.

**Comment by dr-orlovsky** [comment]
> So since you want to support < 1.41.1 I will need to add a feature (I'll call it rust_1_41) since I also implemented From<> for Cow. Without the feature, only Into will be implemented.

Don't worry about that for now; I do not know how to get < 1.41.1 working and do not require it. So it will remain as a WIP PR #9  for now, and if one day we will get it worked, then we will add a feature `rust_1_41`. I will leave a note there

**Comment by dr-orlovsky** [comment]
@Kixunil and you are welcome to merge #8 before opening your PR, if you are ok with it

**Comment by Kixunil** [comment]
So I tested `From` with 1.39 to see if it actually breaks. Turns out it doesn't, presumably because of the type not being generic. So I'm removing the feature.

**Comment by dr-orlovsky** [comment]
And regarding dependencies management here the approach I take: I comment a lot in Cargo.toml and then re-checking everything with each release (only in mission-critical libraries, of course, not everywhere):

https://github.com/LNP-BP/rust-lnpbp/blob/master/Cargo.toml
