### ISSUE TITLE
Create DivRem trait and implement it for all numeric types

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rust-amplify#78]
divmod like operation, returns (quotient, remainder)

**Comment by josediegorobles** [comment]
Hi, in bigint there are this:

// divmod like operation, returns (quotient, remainder)
            #[inline]
            fn div_rem(self, other: Self) -> (Self, Self) {

it has to be the method of the trait?
And implemented in smallint too?

**Comment by josediegorobles** [comment]
I did a pr 
https://github.com/LNP-BP/rust-amplify/pull/96
