### ISSUE TITLE
Constructors for zero, one etc on num types

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rust-amplify#82]

**Comment by 6293** [comment]
Closing because it has already implemented long time ago

https://github.com/LNP-BP/rust-amplify/blob/41d1b476d0d4ab4f859bef8be00dd2b9345c5a2e/num/src/bigint.rs#L65
https://github.com/LNP-BP/rust-amplify/blob/41d1b476d0d4ab4f859bef8be00dd2b9345c5a2e/num/src/smallint.rs#L47
