### ISSUE TITLE
Add #[display(lowercase)] for enums (and uppercase)

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rust-amplify#92]

**Comment by z8674558** [comment]
Hello, I would like to take on this task. Which do you imagine the output of the example below, `withdata` or `withdata(1)`?

```rust
#[derive(Clone, Copy, Debug, Display)]
#[display(lowercase)]
enum En {
     First,
     Second,
     WithData(u8),
 };
println!("{}", En::WithData(1))
```

**Comment by dr-orlovsky** [comment]
@z8674558 thank you for your interest on working on this! I think `withdata(1)` will be the best
